proto_library(
  name = "beam_fn_api_proto",
  srcs = glob(["beam_fn_api.proto"]),
  deps = [
    "//model/pipeline:pipeline_proto",
    "//model/pipeline:endpoints_proto",
    "@com_google_protobuf//:any_proto",
    "@com_google_protobuf//:duration_proto",
    "@com_google_protobuf//:timestamp_proto",
  ],
)

proto_library(
  name = "beam_provision_api_proto",
  srcs = glob(["beam_provision_api.proto"]),
)
