require 'fileutils'
require 'html-proofer'
require 'etc'

task :test do
  HTMLProofer.check_directory("./generated-content", {
    :typhoeus => {
      :timeout => 60,
      :connecttimeout => 40 },
    :allow_hash_href => true,
    :check_html => true,
    :url_ignore => [
        /jstorm.io/,
        /datatorrent.com/,
        /ai.google/, # https://issues.apache.org/jira/browse/INFRA-16527
        /globenewswire.com/, # https://issues.apache.org/jira/browse/BEAM-5518
        /www.se-radio.net/ # BEAM-5611: Can fail with rate limit HTTP 508 error
    ],
    :parallel => { :in_processes => Etc.nprocessors },
    }).run
end
