version: '3'

services:
  # HDFS namenode.
  namenode:
    image: uhopper/hadoop-namenode:2.8.1
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    environment:
      - CLUSTER_NAME=test
    networks:
      - test_net

  # HDFS datanode.
  datanode:
    image: uhopper/hadoop-datanode:2.8.1
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - test_net
    depends_on:
      - "namenode"

  # Integration test.
  test:
    build:
      context: ../../../../../
      dockerfile: sdks/python/apache_beam/io/hdfs_integration_test/Dockerfile
    networks:
      - test_net
    dns:
      # Order matters. The fist server on the list is available on GCE VMs. It
      # is used to resolve the server used for refreshing credentials (used for
      # reading input from GCS). If not running in a GCE VM, the client defaults
      # to anonymous access which should work as well.
      - 169.254.169.254
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - "namenode"
      - "datanode"

networks:
  test_net:
